services:
  payments-service:
    build: .
    container_name: payments-ms
    ports:
      - "8084:8080"
    networks:
      - ecommerce-net
    depends_on:
      payments-postgres:
        condition: service_healthy
      payments-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payments-postgres:5432/payments_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: payments-rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  payments-postgres:
    image: postgres:15-alpine
    container_name: payments-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: payments_db
    ports:
      - "5436:5432"
    volumes:
      - payments-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

  payments-rabbitmq:
    image: rabbitmq:3-management
    container_name: payments-rabbitmq
    restart: always
    ports:
      - "5676:5672"
      - "15676:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true         # <--- Diz: "Não crie, use a que já existe"
    name: ecommerce-network # <--- Tem que ser O MESMO nome definido no Product

volumes:
  payments-postgres-data: