services:
  inventory-service:
    build: .
    container_name: inventory-ms
    ports:
      - "8081:8080"
    networks:
      - ecommerce-net
    depends_on:
      inventory-postgres:
        condition: service_healthy
      inventory-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: inventory-rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  inventory-postgres:
    image: postgres:15-alpine
    container_name: inventory-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory_db
    ports:
      - "5435:5432"
    volumes:
      - inventory-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

  inventory-rabbitmq:
    image: rabbitmq:3-management
    container_name: inventory-rabbitmq
    restart: always
    ports:
      - "5675:5672"
      - "15675:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true         # <--- Diz: "Não crie, use a que já existe"
    name: ecommerce-network # <--- Tem que ser O MESMO nome definido no Product

volumes:
  inventory-postgres-data: