services:
  # --- Serviço 1: Banco de Dados (PostgreSQL) ---
  postgresdb:
    image: postgres:15-alpine  # Versão leve (Alpine)
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres  # Usuário padrão
      POSTGRES_PASSWORD: root  # Senha
      POSTGRES_DB: user_db  # Cria um banco inicial padrão
    ports:
      - "5432:5432" # Porta padrão do Postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # O caminho interno muda em relação ao MySQL

    networks:           # <--- ADICIONADO
      - ecommerce-net   # O banco entra na rede

  # --- Serviço 2: Mensageria (RabbitMQ - Mantém igual) ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
    networks:           # <--- ADICIONADO
      - ecommerce-net   # A mensageria entra na rede

networks:
  ecommerce-net:
    external: true         # <--- Diz: "Não crie, use a que já existe"
    name: ecommerce-network # <--- Tem que ser O MESMO nome definido no Product